/* department table */
CREATE TABLE IF NOT EXISTS DEPARTMENT (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR (20) NOT NULL,
  NOTES VARCHAR (100)
);

/* department table */
CREATE TABLE IF NOT EXISTS EMPLOYEE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  /* FK */
  DEPARTMENT_ID INTEGER NOT NULL,
  FNAME VARCHAR (20) NOT NULL,
  LNAME VARCHAR (20) NOT NULL,
  IS_MANAGER TINYINT, 
  SSN INTEGER, 
  NOTES VARCHAR (100),

  /* FK CONSTRAINT */
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID)
);
